name: 'Simple Github Action'
author: 'Nils Gaehlert'
description: 'Simple Github Action based on Docker'

inputs:
    program:
        description: 'Program to be called'
        required: true
        default: 'echo "Hello World from Program to be called!"'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.program }}
outputs:
    time:
        description: 'Action Completed'