name: 'Simple Github Action'
author: 'Nils Gaehlert'
description: 'Simple Github Action based on Docker'

inputs:
    program:
        description: 'python '
        required: true
        default: 'python --version'
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.program }}
outputs:
    time:
        description: 'Action Completed'